import {
  CountriesModel,
} from '../models/CountriesModel';

const countries: Array<CountriesModel> = [
  {
    iso_3166_1: 'AD',
    english_name: 'Andorra',
    text: 'Andorra',
    value: 'ad',
    flag: 'ad',
  },
  {
    iso_3166_1: 'AE',
    english_name: 'United Arab Emirates',
    text: 'United Arab Emirates',
    value: 'ae',
    flag: 'ae',
  },
  {
    iso_3166_1: 'AF',
    english_name: 'Afghanistan',
    text: 'Afghanistan',
    value: 'af',
    flag: 'af',
  },
  {
    iso_3166_1: 'AG',
    english_name: 'Antigua and Barbuda',
    text: 'Antigua and Barbuda',
    value: 'ag',
    flag: 'ag',
  },
  {
    iso_3166_1: 'AI',
    english_name: 'Anguilla',
    text: 'Anguilla',
    value: 'ai',
    flag: 'ai',
  },
  {
    iso_3166_1: 'AL',
    english_name: 'Albania',
    text: 'Albania',
    value: 'al',
    flag: 'al',
  },
  {
    iso_3166_1: 'AM',
    english_name: 'Armenia',
    text: 'Armenia',
    value: 'am',
    flag: 'am',
  },
  {
    iso_3166_1: 'AN',
    english_name: 'Netherlands Antilles',
    text: 'Netherlands Antilles',
    value: 'an',
    flag: 'an',
  },
  {
    iso_3166_1: 'AO',
    english_name: 'Angola',
    text: 'Angola',
    value: 'ao',
    flag: 'ao',
  },
  {
    iso_3166_1: 'AQ',
    english_name: 'Antarctica',
    text: 'Antarctica',
    value: 'aq',
    flag: 'aq',
  },
  {
    iso_3166_1: 'AR',
    english_name: 'Argentina',
    text: 'Argentina',
    value: 'ar',
    flag: 'ar',
  },
  {
    iso_3166_1: 'AS',
    english_name: 'American Samoa',
    text: 'American Samoa',
    value: 'as',
    flag: 'as',
  },
  {
    iso_3166_1: 'AT',
    english_name: 'Austria',
    text: 'Austria',
    value: 'at',
    flag: 'at',
  },
  {
    iso_3166_1: 'AU',
    english_name: 'Australia',
    text: 'Australia',
    value: 'au',
    flag: 'au',
  },
  {
    iso_3166_1: 'AW',
    english_name: 'Aruba',
    text: 'Aruba',
    value: 'aw',
    flag: 'aw',
  },
  {
    iso_3166_1: 'AZ',
    english_name: 'Azerbaijan',
    text: 'Azerbaijan',
    value: 'az',
    flag: 'az',
  },
  {
    iso_3166_1: 'BA',
    english_name: 'Bosnia and Herzegovina',
    text: 'Bosnia and Herzegovina',
    value: 'ba',
    flag: 'ba',
  },
  {
    iso_3166_1: 'BB',
    english_name: 'Barbados',
    text: 'Barbados',
    value: 'bb',
    flag: 'bb',
  },
  {
    iso_3166_1: 'BD',
    english_name: 'Bangladesh',
    text: 'Bangladesh',
    value: 'bd',
    flag: 'bd',
  },
  {
    iso_3166_1: 'BE',
    english_name: 'Belgium',
    text: 'Belgium',
    value: 'be',
    flag: 'be',
  },
  {
    iso_3166_1: 'BF',
    english_name: 'Burkina Faso',
    text: 'Burkina Faso',
    value: 'bf',
    flag: 'bf',
  },
  {
    iso_3166_1: 'BG',
    english_name: 'Bulgaria',
    text: 'Bulgaria',
    value: 'bg',
    flag: 'bg',
  },
  {
    iso_3166_1: 'BH',
    english_name: 'Bahrain',
    text: 'Bahrain',
    value: 'bh',
    flag: 'bh',
  },
  {
    iso_3166_1: 'BI',
    english_name: 'Burundi',
    text: 'Burundi',
    value: 'bi',
    flag: 'bi',
  },
  {
    iso_3166_1: 'BJ',
    english_name: 'Benin',
    text: 'Benin',
    value: 'bj',
    flag: 'bj',
  },
  {
    iso_3166_1: 'BM',
    english_name: 'Bermuda',
    text: 'Bermuda',
    value: 'bm',
    flag: 'bm',
  },
  {
    iso_3166_1: 'BN',
    english_name: 'Brunei Darussalam',
    text: 'Brunei Darussalam',
    value: 'bn',
    flag: 'bn',
  },
  {
    iso_3166_1: 'BO',
    english_name: 'Bolivia',
    text: 'Bolivia',
    value: 'bo',
    flag: 'bo',
  },
  {
    iso_3166_1: 'BR',
    english_name: 'Brazil',
    text: 'Brazil',
    value: 'br',
    flag: 'br',
  },
  {
    iso_3166_1: 'BS',
    english_name: 'Bahamas',
    text: 'Bahamas',
    value: 'bs',
    flag: 'bs',
  },
  {
    iso_3166_1: 'BT',
    english_name: 'Bhutan',
    text: 'Bhutan',
    value: 'bt',
    flag: 'bt',
  },
  {
    iso_3166_1: 'BV',
    english_name: 'Bouvet Island',
    text: 'Bouvet Island',
    value: 'bv',
    flag: 'bv',
  },
  {
    iso_3166_1: 'BW',
    english_name: 'Botswana',
    text: 'Botswana',
    value: 'bw',
    flag: 'bw',
  },
  {
    iso_3166_1: 'BZ',
    english_name: 'Belize',
    text: 'Belize',
    value: 'bz',
    flag: 'bz',
  },
  {
    iso_3166_1: 'BY',
    english_name: 'Belarus',
    text: 'Belarus',
    value: 'by',
    flag: 'by',
  },
  {
    iso_3166_1: 'CA',
    english_name: 'Canada',
    text: 'Canada',
    value: 'ca',
    flag: 'ca',
  },
  {
    iso_3166_1: 'CC',
    english_name: 'Cocos  Islands',
    text: 'Cocos  Islands',
    value: 'cc',
    flag: 'cc',
  },
  {
    iso_3166_1: 'CD',
    english_name: 'Congo',
    text: 'Congo',
    value: 'cd',
    flag: 'cd',
  },
  {
    iso_3166_1: 'CF',
    english_name: 'Central African Republic',
    text: 'Central African Republic',
    value: 'cf',
    flag: 'cf',
  },
  {
    iso_3166_1: 'CG',
    english_name: 'Congo',
    text: 'Congo',
    value: 'cg',
    flag: 'cg',
  },
  {
    iso_3166_1: 'CH',
    english_name: 'Switzerland',
    text: 'Switzerland',
    value: 'ch',
    flag: 'ch',
  },
  {
    iso_3166_1: 'CI',
    english_name: "Cote D'Ivoire",
    text: "Cote D'Ivoire",
    value: 'ci',
    flag: 'ci',
  },
  {
    iso_3166_1: 'CK',
    english_name: 'Cook Islands',
    text: 'Cook Islands',
    value: 'ck',
    flag: 'ck',
  },
  {
    iso_3166_1: 'CL',
    english_name: 'Chile',
    text: 'Chile',
    value: 'cl',
    flag: 'cl',
  },
  {
    iso_3166_1: 'CM',
    english_name: 'Cameroon',
    text: 'Cameroon',
    value: 'cm',
    flag: 'cm',
  },
  {
    iso_3166_1: 'CN',
    english_name: 'China',
    text: 'China',
    value: 'cn',
    flag: 'cn',
  },
  {
    iso_3166_1: 'CO',
    english_name: 'Colombia',
    text: 'Colombia',
    value: 'co',
    flag: 'co',
  },
  {
    iso_3166_1: 'CR',
    english_name: 'Costa Rica',
    text: 'Costa Rica',
    value: 'cr',
    flag: 'cr',
  },
  {
    iso_3166_1: 'CS',
    english_name: 'Serbia and Montenegro',
    text: 'Serbia and Montenegro',
    value: 'cs',
    flag: 'cs',
  },
  {
    iso_3166_1: 'CU',
    english_name: 'Cuba',
    text: 'Cuba',
    value: 'cu',
    flag: 'cu',
  },
  {
    iso_3166_1: 'CV',
    english_name: 'Cape Verde',
    text: 'Cape Verde',
    value: 'cv',
    flag: 'cv',
  },
  {
    iso_3166_1: 'CX',
    english_name: 'Christmas Island',
    text: 'Christmas Island',
    value: 'cx',
    flag: 'cx',
  },
  {
    iso_3166_1: 'CY',
    english_name: 'Cyprus',
    text: 'Cyprus',
    value: 'cy',
    flag: 'cy',
  },
  {
    iso_3166_1: 'CZ',
    english_name: 'Czech Republic',
    text: 'Czech Republic',
    value: 'cz',
    flag: 'cz',
  },
  {
    iso_3166_1: 'DE',
    english_name: 'Germany',
    text: 'Germany',
    value: 'de',
    flag: 'de',
  },
  {
    iso_3166_1: 'DJ',
    english_name: 'Djibouti',
    text: 'Djibouti',
    value: 'dj',
    flag: 'dj',
  },
  {
    iso_3166_1: 'DK',
    english_name: 'Denmark',
    text: 'Denmark',
    value: 'dk',
    flag: 'dk',
  },
  {
    iso_3166_1: 'DM',
    english_name: 'Dominica',
    text: 'Dominica',
    value: 'dm',
    flag: 'dm',
  },
  {
    iso_3166_1: 'DO',
    english_name: 'Dominican Republic',
    text: 'Dominican Republic',
    value: 'do',
    flag: 'do',
  },
  {
    iso_3166_1: 'DZ',
    english_name: 'Algeria',
    text: 'Algeria',
    value: 'dz',
    flag: 'dz',
  },
  {
    iso_3166_1: 'EC',
    english_name: 'Ecuador',
    text: 'Ecuador',
    value: 'ec',
    flag: 'ec',
  },
  {
    iso_3166_1: 'EE',
    english_name: 'Estonia',
    text: 'Estonia',
    value: 'ee',
    flag: 'ee',
  },
  {
    iso_3166_1: 'EG',
    english_name: 'Egypt',
    text: 'Egypt',
    value: 'eg',
    flag: 'eg',
  },
  {
    iso_3166_1: 'EH',
    english_name: 'Western Sahara',
    text: 'Western Sahara',
    value: 'eh',
    flag: 'eh',
  },
  {
    iso_3166_1: 'ER',
    english_name: 'Eritrea',
    text: 'Eritrea',
    value: 'er',
    flag: 'er',
  },
  {
    iso_3166_1: 'ES',
    english_name: 'Spain',
    text: 'Spain',
    value: 'es',
    flag: 'es',
  },
  {
    iso_3166_1: 'ET',
    english_name: 'Ethiopia',
    text: 'Ethiopia',
    value: 'et',
    flag: 'et',
  },
  {
    iso_3166_1: 'FI',
    english_name: 'Finland',
    text: 'Finland',
    value: 'fi',
    flag: 'fi',
  },
  {
    iso_3166_1: 'FJ',
    english_name: 'Fiji',
    text: 'Fiji',
    value: 'fj',
    flag: 'fj',
  },
  {
    iso_3166_1: 'FK',
    english_name: 'Falkland Islands',
    text: 'Falkland Islands',
    value: 'fk',
    flag: 'fk',
  },
  {
    iso_3166_1: 'RS',
    english_name: 'Serbia',
    text: 'Serbia',
    value: 'rs',
    flag: 'rs',
  },
  {
    iso_3166_1: 'FM',
    english_name: 'Micronesia',
    text: 'Micronesia',
    value: 'fm',
    flag: 'fm',
  },
  {
    iso_3166_1: 'FO',
    english_name: 'Faeroe Islands',
    text: 'Faeroe Islands',
    value: 'fo',
    flag: 'fo',
  },
  {
    iso_3166_1: 'FR',
    english_name: 'France',
    text: 'France',
    value: 'fr',
    flag: 'fr',
  },
  {
    iso_3166_1: 'GA',
    english_name: 'Gabon',
    text: 'Gabon',
    value: 'ga',
    flag: 'ga',
  },
  {
    iso_3166_1: 'GB',
    english_name: 'United Kingdom',
    text: 'United Kingdom',
    value: 'gb',
    flag: 'gb',
  },
  {
    iso_3166_1: 'GD',
    english_name: 'Grenada',
    text: 'Grenada',
    value: 'gd',
    flag: 'gd',
  },
  {
    iso_3166_1: 'GE',
    english_name: 'Georgia',
    text: 'Georgia',
    value: 'ge',
    flag: 'ge',
  },
  {
    iso_3166_1: 'GF',
    english_name: 'French Guiana',
    text: 'French Guiana',
    value: 'gf',
    flag: 'gf',
  },
  {
    iso_3166_1: 'GH',
    english_name: 'Ghana',
    text: 'Ghana',
    value: 'gh',
    flag: 'gh',
  },
  {
    iso_3166_1: 'GI',
    english_name: 'Gibraltar',
    text: 'Gibraltar',
    value: 'gi',
    flag: 'gi',
  },
  {
    iso_3166_1: 'GL',
    english_name: 'Greenland',
    text: 'Greenland',
    value: 'gl',
    flag: 'gl',
  },
  {
    iso_3166_1: 'GM',
    english_name: 'Gambia',
    text: 'Gambia',
    value: 'gm',
    flag: 'gm',
  },
  {
    iso_3166_1: 'GN',
    english_name: 'Guinea',
    text: 'Guinea',
    value: 'gn',
    flag: 'gn',
  },
  {
    iso_3166_1: 'GP',
    english_name: 'Guadaloupe',
    text: 'Guadaloupe',
    value: 'gp',
    flag: 'gp',
  },
  {
    iso_3166_1: 'GQ',
    english_name: 'Equatorial Guinea',
    text: 'Equatorial Guinea',
    value: 'gq',
    flag: 'gq',
  },
  {
    iso_3166_1: 'GR',
    english_name: 'Greece',
    text: 'Greece',
    value: 'gr',
    flag: 'gr',
  },
  {
    iso_3166_1: 'GS',
    english_name: 'South Georgia and the South Sandwich Islands',
    text: 'South Georgia and the South Sandwich Islands',
    value: 'gs',
    flag: 'gs',
  },
  {
    iso_3166_1: 'GT',
    english_name: 'Guatemala',
    text: 'Guatemala',
    value: 'gt',
    flag: 'gt',
  },
  {
    iso_3166_1: 'GU',
    english_name: 'Guam',
    text: 'Guam',
    value: 'gu',
    flag: 'gu',
  },
  {
    iso_3166_1: 'GW',
    english_name: 'Guinea-Bissau',
    text: 'Guinea-Bissau',
    value: 'gw',
    flag: 'gw',
  },
  {
    iso_3166_1: 'GY',
    english_name: 'Guyana',
    text: 'Guyana',
    value: 'gy',
    flag: 'gy',
  },
  {
    iso_3166_1: 'HK',
    english_name: 'Hong Kong',
    text: 'Hong Kong',
    value: 'hk',
    flag: 'hk',
  },
  {
    iso_3166_1: 'HM',
    english_name: 'Heard and McDonald Islands',
    text: 'Heard and McDonald Islands',
    value: 'hm',
    flag: 'hm',
  },
  {
    iso_3166_1: 'HN',
    english_name: 'Honduras',
    text: 'Honduras',
    value: 'hn',
    flag: 'hn',
  },
  {
    iso_3166_1: 'HR',
    english_name: 'Croatia',
    text: 'Croatia',
    value: 'hr',
    flag: 'hr',
  },
  {
    iso_3166_1: 'HT',
    english_name: 'Haiti',
    text: 'Haiti',
    value: 'ht',
    flag: 'ht',
  },
  {
    iso_3166_1: 'HU',
    english_name: 'Hungary',
    text: 'Hungary',
    value: 'hu',
    flag: 'hu',
  },
  {
    iso_3166_1: 'ID',
    english_name: 'Indonesia',
    text: 'Indonesia',
    value: 'id',
    flag: 'id',
  },
  {
    iso_3166_1: 'IE',
    english_name: 'Ireland',
    text: 'Ireland',
    value: 'ie',
    flag: 'ie',
  },
  {
    iso_3166_1: 'IL',
    english_name: 'Israel',
    text: 'Israel',
    value: 'il',
    flag: 'il',
  },
  {
    iso_3166_1: 'IN',
    english_name: 'India',
    text: 'India',
    value: 'in',
    flag: 'in',
  },
  {
    iso_3166_1: 'IO',
    english_name: 'British Indian Ocean Territory',
    text: 'British Indian Ocean Territory',
    value: 'io',
    flag: 'io',
  },
  {
    iso_3166_1: 'IQ',
    english_name: 'Iraq',
    text: 'Iraq',
    value: 'iq',
    flag: 'iq',
  },
  {
    iso_3166_1: 'IR',
    english_name: 'Iran',
    text: 'Iran',
    value: 'ir',
    flag: 'ir',
  },
  {
    iso_3166_1: 'IS',
    english_name: 'Iceland',
    text: 'Iceland',
    value: 'is',
    flag: 'is',
  },
  {
    iso_3166_1: 'IT',
    english_name: 'Italy',
    text: 'Italy',
    value: 'it',
    flag: 'it',
  },
  {
    iso_3166_1: 'JM',
    english_name: 'Jamaica',
    text: 'Jamaica',
    value: 'jm',
    flag: 'jm',
  },
  {
    iso_3166_1: 'JO',
    english_name: 'Jordan',
    text: 'Jordan',
    value: 'jo',
    flag: 'jo',
  },
  {
    iso_3166_1: 'JP',
    english_name: 'Japan',
    text: 'Japan',
    value: 'jp',
    flag: 'jp',
  },
  {
    iso_3166_1: 'KE',
    english_name: 'Kenya',
    text: 'Kenya',
    value: 'ke',
    flag: 'ke',
  },
  {
    iso_3166_1: 'KG',
    english_name: 'Kyrgyz Republic',
    text: 'Kyrgyz Republic',
    value: 'kg',
    flag: 'kg',
  },
  {
    iso_3166_1: 'KH',
    english_name: 'Cambodia',
    text: 'Cambodia',
    value: 'kh',
    flag: 'kh',
  },
  {
    iso_3166_1: 'KI',
    english_name: 'Kiribati',
    text: 'Kiribati',
    value: 'ki',
    flag: 'ki',
  },
  {
    iso_3166_1: 'KM',
    english_name: 'Comoros',
    text: 'Comoros',
    value: 'km',
    flag: 'km',
  },
  {
    iso_3166_1: 'KN',
    english_name: 'St. Kitts and Nevis',
    text: 'St. Kitts and Nevis',
    value: 'kn',
    flag: 'kn',
  },
  {
    iso_3166_1: 'KP',
    english_name: 'North Korea',
    text: 'North Korea',
    value: 'kp',
    flag: 'kp',
  },
  {
    iso_3166_1: 'KW',
    english_name: 'Kuwait',
    text: 'Kuwait',
    value: 'kw',
    flag: 'kw',
  },
  {
    iso_3166_1: 'KY',
    english_name: 'Cayman Islands',
    text: 'Cayman Islands',
    value: 'ky',
    flag: 'ky',
  },
  {
    iso_3166_1: 'KZ',
    english_name: 'Kazakhstan',
    text: 'Kazakhstan',
    value: 'kz',
    flag: 'kz',
  },
  {
    iso_3166_1: 'LA',
    english_name: "Lao People's Democratic Republic",
    text: "Lao People's Democratic Republic",
    value: 'la',
    flag: 'la',
  },
  {
    iso_3166_1: 'LB',
    english_name: 'Lebanon',
    text: 'Lebanon',
    value: 'lb',
    flag: 'lb',
  },
  {
    iso_3166_1: 'LC',
    english_name: 'St. Lucia',
    text: 'St. Lucia',
    value: 'lc',
    flag: 'lc',
  },
  {
    iso_3166_1: 'LI',
    english_name: 'Liechtenstein',
    text: 'Liechtenstein',
    value: 'li',
    flag: 'li',
  },
  {
    iso_3166_1: 'LK',
    english_name: 'Sri Lanka',
    text: 'Sri Lanka',
    value: 'lk',
    flag: 'lk',
  },
  {
    iso_3166_1: 'LR',
    english_name: 'Liberia',
    text: 'Liberia',
    value: 'lr',
    flag: 'lr',
  },
  {
    iso_3166_1: 'LS',
    english_name: 'Lesotho',
    text: 'Lesotho',
    value: 'ls',
    flag: 'ls',
  },
  {
    iso_3166_1: 'LT',
    english_name: 'Lithuania',
    text: 'Lithuania',
    value: 'lt',
    flag: 'lt',
  },
  {
    iso_3166_1: 'LU',
    english_name: 'Luxembourg',
    text: 'Luxembourg',
    value: 'lu',
    flag: 'lu',
  },
  {
    iso_3166_1: 'LV',
    english_name: 'Latvia',
    text: 'Latvia',
    value: 'lv',
    flag: 'lv',
  },
  {
    iso_3166_1: 'LY',
    english_name: 'Libyan Arab Jamahiriya',
    text: 'Libyan Arab Jamahiriya',
    value: 'ly',
    flag: 'ly',
  },
  {
    iso_3166_1: 'MA',
    english_name: 'Morocco',
    text: 'Morocco',
    value: 'ma',
    flag: 'ma',
  },
  {
    iso_3166_1: 'MC',
    english_name: 'Monaco',
    text: 'Monaco',
    value: 'mc',
    flag: 'mc',
  },
  {
    iso_3166_1: 'MD',
    english_name: 'Moldova',
    text: 'Moldova',
    value: 'md',
    flag: 'md',
  },
  {
    iso_3166_1: 'MG',
    english_name: 'Madagascar',
    text: 'Madagascar',
    value: 'mg',
    flag: 'mg',
  },
  {
    iso_3166_1: 'MH',
    english_name: 'Marshall Islands',
    text: 'Marshall Islands',
    value: 'mh',
    flag: 'mh',
  },
  {
    iso_3166_1: 'MK',
    english_name: 'Macedonia',
    text: 'Macedonia',
    value: 'mk',
    flag: 'mk',
  },
  {
    iso_3166_1: 'ML',
    english_name: 'Mali',
    text: 'Mali',
    value: 'ml',
    flag: 'ml',
  },
  {
    iso_3166_1: 'MM',
    english_name: 'Myanmar',
    text: 'Myanmar',
    value: 'mm',
    flag: 'mm',
  },
  {
    iso_3166_1: 'MN',
    english_name: 'Mongolia',
    text: 'Mongolia',
    value: 'mn',
    flag: 'mn',
  },
  {
    iso_3166_1: 'MO',
    english_name: 'Macao',
    text: 'Macao',
    value: 'mo',
    flag: 'mo',
  },
  {
    iso_3166_1: 'MP',
    english_name: 'Northern Mariana Islands',
    text: 'Northern Mariana Islands',
    value: 'mp',
    flag: 'mp',
  },
  {
    iso_3166_1: 'MQ',
    english_name: 'Martinique',
    text: 'Martinique',
    value: 'mq',
    flag: 'mq',
  },
  {
    iso_3166_1: 'MR',
    english_name: 'Mauritania',
    text: 'Mauritania',
    value: 'mr',
    flag: 'mr',
  },
  {
    iso_3166_1: 'MS',
    english_name: 'Montserrat',
    text: 'Montserrat',
    value: 'ms',
    flag: 'ms',
  },
  {
    iso_3166_1: 'MT',
    english_name: 'Malta',
    text: 'Malta',
    value: 'mt',
    flag: 'mt',
  },
  {
    iso_3166_1: 'MU',
    english_name: 'Mauritius',
    text: 'Mauritius',
    value: 'mu',
    flag: 'mu',
  },
  {
    iso_3166_1: 'MV',
    english_name: 'Maldives',
    text: 'Maldives',
    value: 'mv',
    flag: 'mv',
  },
  {
    iso_3166_1: 'MW',
    english_name: 'Malawi',
    text: 'Malawi',
    value: 'mw',
    flag: 'mw',
  },
  {
    iso_3166_1: 'MX',
    english_name: 'Mexico',
    text: 'Mexico',
    value: 'mx',
    flag: 'mx',
  },
  {
    iso_3166_1: 'MY',
    english_name: 'Malaysia',
    text: 'Malaysia',
    value: 'my',
    flag: 'my',
  },
  {
    iso_3166_1: 'MZ',
    english_name: 'Mozambique',
    text: 'Mozambique',
    value: 'mz',
    flag: 'mz',
  },
  {
    iso_3166_1: 'NA',
    english_name: 'Namibia',
    text: 'Namibia',
    value: 'na',
    flag: 'na',
  },
  {
    iso_3166_1: 'NC',
    english_name: 'New Caledonia',
    text: 'New Caledonia',
    value: 'nc',
    flag: 'nc',
  },
  {
    iso_3166_1: 'NE',
    english_name: 'Niger',
    text: 'Niger',
    value: 'ne',
    flag: 'ne',
  },
  {
    iso_3166_1: 'NF',
    english_name: 'Norfolk Island',
    text: 'Norfolk Island',
    value: 'nf',
    flag: 'nf',
  },
  {
    iso_3166_1: 'NG',
    english_name: 'Nigeria',
    text: 'Nigeria',
    value: 'ng',
    flag: 'ng',
  },
  {
    iso_3166_1: 'ME',
    english_name: 'Montenegro',
    text: 'Montenegro',
    value: 'me',
    flag: 'me',
  },
  {
    iso_3166_1: 'NI',
    english_name: 'Nicaragua',
    text: 'Nicaragua',
    value: 'ni',
    flag: 'ni',
  },
  {
    iso_3166_1: 'NL',
    english_name: 'Netherlands',
    text: 'Netherlands',
    value: 'nl',
    flag: 'nl',
  },
  {
    iso_3166_1: 'NO',
    english_name: 'Norway',
    text: 'Norway',
    value: 'no',
    flag: 'no',
  },
  {
    iso_3166_1: 'NP',
    english_name: 'Nepal',
    text: 'Nepal',
    value: 'np',
    flag: 'np',
  },
  {
    iso_3166_1: 'NR',
    english_name: 'Nauru',
    text: 'Nauru',
    value: 'nr',
    flag: 'nr',
  },
  {
    iso_3166_1: 'NU',
    english_name: 'Niue',
    text: 'Niue',
    value: 'nu',
    flag: 'nu',
  },
  {
    iso_3166_1: 'NZ',
    english_name: 'New Zealand',
    text: 'New Zealand',
    value: 'nz',
    flag: 'nz',
  },
  {
    iso_3166_1: 'OM',
    english_name: 'Oman',
    text: 'Oman',
    value: 'om',
    flag: 'om',
  },
  {
    iso_3166_1: 'PA',
    english_name: 'Panama',
    text: 'Panama',
    value: 'pa',
    flag: 'pa',
  },
  {
    iso_3166_1: 'PE',
    english_name: 'Peru',
    text: 'Peru',
    value: 'pe',
    flag: 'pe',
  },
  {
    iso_3166_1: 'PF',
    english_name: 'French Polynesia',
    text: 'French Polynesia',
    value: 'pf',
    flag: 'pf',
  },
  {
    iso_3166_1: 'PG',
    english_name: 'Papua New Guinea',
    text: 'Papua New Guinea',
    value: 'pg',
    flag: 'pg',
  },
  {
    iso_3166_1: 'PH',
    english_name: 'Philippines',
    text: 'Philippines',
    value: 'ph',
    flag: 'ph',
  },
  {
    iso_3166_1: 'YU',
    english_name: 'Yugoslavia',
    text: 'Yugoslavia',
    value: 'yu',
    flag: 'yu',
  },
  {
    iso_3166_1: 'XK',
    english_name: 'Kosovo',
    text: 'Kosovo',
    value: 'xk',
    flag: 'xk',
  },
  {
    iso_3166_1: 'XC',
    english_name: 'Czechoslovakia',
    text: 'Czechoslovakia',
    value: 'xc',
    flag: 'xc',
  },
  {
    iso_3166_1: 'PK',
    english_name: 'Pakistan',
    text: 'Pakistan',
    value: 'pk',
    flag: 'pk',
  },
  {
    iso_3166_1: 'PL',
    english_name: 'Poland',
    text: 'Poland',
    value: 'pl',
    flag: 'pl',
  },
  {
    iso_3166_1: 'PM',
    english_name: 'St. Pierre and Miquelon',
    text: 'St. Pierre and Miquelon',
    value: 'pm',
    flag: 'pm',
  },
  {
    iso_3166_1: 'PN',
    english_name: 'Pitcairn Island',
    text: 'Pitcairn Island',
    value: 'pn',
    flag: 'pn',
  },
  {
    iso_3166_1: 'PR',
    english_name: 'Puerto Rico',
    text: 'Puerto Rico',
    value: 'pr',
    flag: 'pr',
  },
  {
    iso_3166_1: 'PS',
    english_name: 'Palestinian Territory',
    text: 'Palestinian Territory',
    value: 'ps',
    flag: 'ps',
  },
  {
    iso_3166_1: 'PT',
    english_name: 'Portugal',
    text: 'Portugal',
    value: 'pt',
    flag: 'pt',
  },
  {
    iso_3166_1: 'PW',
    english_name: 'Palau',
    text: 'Palau',
    value: 'pw',
    flag: 'pw',
  },
  {
    iso_3166_1: 'PY',
    english_name: 'Paraguay',
    text: 'Paraguay',
    value: 'py',
    flag: 'py',
  },
  {
    iso_3166_1: 'QA',
    english_name: 'Qatar',
    text: 'Qatar',
    value: 'qa',
    flag: 'qa',
  },
  {
    iso_3166_1: 'RE',
    english_name: 'Reunion',
    text: 'Reunion',
    value: 're',
    flag: 're',
  },
  {
    iso_3166_1: 'RO',
    english_name: 'Romania',
    text: 'Romania',
    value: 'ro',
    flag: 'ro',
  },
  {
    iso_3166_1: 'RU',
    english_name: 'Russia',
    text: 'Russia',
    value: 'ru',
    flag: 'ru',
  },
  {
    iso_3166_1: 'RW',
    english_name: 'Rwanda',
    text: 'Rwanda',
    value: 'rw',
    flag: 'rw',
  },
  {
    iso_3166_1: 'SA',
    english_name: 'Saudi Arabia',
    text: 'Saudi Arabia',
    value: 'sa',
    flag: 'sa',
  },
  {
    iso_3166_1: 'SB',
    english_name: 'Solomon Islands',
    text: 'Solomon Islands',
    value: 'sb',
    flag: 'sb',
  },
  {
    iso_3166_1: 'SC',
    english_name: 'Seychelles',
    text: 'Seychelles',
    value: 'sc',
    flag: 'sc',
  },
  {
    iso_3166_1: 'SD',
    english_name: 'Sudan',
    text: 'Sudan',
    value: 'sd',
    flag: 'sd',
  },
  {
    iso_3166_1: 'SE',
    english_name: 'Sweden',
    text: 'Sweden',
    value: 'se',
    flag: 'se',
  },
  {
    iso_3166_1: 'SG',
    english_name: 'Singapore',
    text: 'Singapore',
    value: 'sg',
    flag: 'sg',
  },
  {
    iso_3166_1: 'SH',
    english_name: 'St. Helena',
    text: 'St. Helena',
    value: 'sh',
    flag: 'sh',
  },
  {
    iso_3166_1: 'SI',
    english_name: 'Slovenia',
    text: 'Slovenia',
    value: 'si',
    flag: 'si',
  },
  {
    iso_3166_1: 'SJ',
    english_name: 'Svalbard & Jan Mayen Islands',
    text: 'Svalbard & Jan Mayen Islands',
    value: 'sj',
    flag: 'sj',
  },
  {
    iso_3166_1: 'SK',
    english_name: 'Slovakia',
    text: 'Slovakia',
    value: 'sk',
    flag: 'sk',
  },
  {
    iso_3166_1: 'SL',
    english_name: 'Sierra Leone',
    text: 'Sierra Leone',
    value: 'sl',
    flag: 'sl',
  },
  {
    iso_3166_1: 'SM',
    english_name: 'San Marino',
    text: 'San Marino',
    value: 'sm',
    flag: 'sm',
  },
  {
    iso_3166_1: 'SN',
    english_name: 'Senegal',
    text: 'Senegal',
    value: 'sn',
    flag: 'sn',
  },
  {
    iso_3166_1: 'SO',
    english_name: 'Somalia',
    text: 'Somalia',
    value: 'so',
    flag: 'so',
  },
  {
    iso_3166_1: 'SR',
    english_name: 'Suriname',
    text: 'Suriname',
    value: 'sr',
    flag: 'sr',
  },
  {
    iso_3166_1: 'ST',
    english_name: 'Sao Tome and Principe',
    text: 'Sao Tome and Principe',
    value: 'st',
    flag: 'st',
  },
  {
    iso_3166_1: 'SV',
    english_name: 'El Salvador',
    text: 'El Salvador',
    value: 'sv',
    flag: 'sv',
  },
  {
    iso_3166_1: 'SY',
    english_name: 'Syrian Arab Republic',
    text: 'Syrian Arab Republic',
    value: 'sy',
    flag: 'sy',
  },
  {
    iso_3166_1: 'SZ',
    english_name: 'Swaziland',
    text: 'Swaziland',
    value: 'sz',
    flag: 'sz',
  },
  {
    iso_3166_1: 'TC',
    english_name: 'Turks and Caicos Islands',
    text: 'Turks and Caicos Islands',
    value: 'tc',
    flag: 'tc',
  },
  {
    iso_3166_1: 'TD',
    english_name: 'Chad',
    text: 'Chad',
    value: 'td',
    flag: 'td',
  },
  {
    iso_3166_1: 'TF',
    english_name: 'French Southern Territories',
    text: 'French Southern Territories',
    value: 'tf',
    flag: 'tf',
  },
  {
    iso_3166_1: 'TG',
    english_name: 'Togo',
    text: 'Togo',
    value: 'tg',
    flag: 'tg',
  },
  {
    iso_3166_1: 'TH',
    english_name: 'Thailand',
    text: 'Thailand',
    value: 'th',
    flag: 'th',
  },
  {
    iso_3166_1: 'TJ',
    english_name: 'Tajikistan',
    text: 'Tajikistan',
    value: 'tj',
    flag: 'tj',
  },
  {
    iso_3166_1: 'TK',
    english_name: 'Tokelau',
    text: 'Tokelau',
    value: 'tk',
    flag: 'tk',
  },
  {
    iso_3166_1: 'TL',
    english_name: 'Timor-Leste',
    text: 'Timor-Leste',
    value: 'tl',
    flag: 'tl',
  },
  {
    iso_3166_1: 'TM',
    english_name: 'Turkmenistan',
    text: 'Turkmenistan',
    value: 'tm',
    flag: 'tm',
  },
  {
    iso_3166_1: 'TN',
    english_name: 'Tunisia',
    text: 'Tunisia',
    value: 'tn',
    flag: 'tn',
  },
  {
    iso_3166_1: 'TO',
    english_name: 'Tonga',
    text: 'Tonga',
    value: 'to',
    flag: 'to',
  },
  {
    iso_3166_1: 'TR',
    english_name: 'Turkey',
    text: 'Turkey',
    value: 'tr',
    flag: 'tr',
  },
  {
    iso_3166_1: 'TT',
    english_name: 'Trinidad and Tobago',
    text: 'Trinidad and Tobago',
    value: 'tt',
    flag: 'tt',
  },
  {
    iso_3166_1: 'TV',
    english_name: 'Tuvalu',
    text: 'Tuvalu',
    value: 'tv',
    flag: 'tv',
  },
  {
    iso_3166_1: 'TW',
    english_name: 'Taiwan',
    text: 'Taiwan',
    value: 'tw',
    flag: 'tw',
  },
  {
    iso_3166_1: 'TZ',
    english_name: 'Tanzania',
    text: 'Tanzania',
    value: 'tz',
    flag: 'tz',
  },
  {
    iso_3166_1: 'UA',
    english_name: 'Ukraine',
    text: 'Ukraine',
    value: 'ua',
    flag: 'ua',
  },
  {
    iso_3166_1: 'UG',
    english_name: 'Uganda',
    text: 'Uganda',
    value: 'ug',
    flag: 'ug',
  },
  {
    iso_3166_1: 'UM',
    english_name: 'United States Minor Outlying Islands',
    text: 'United States Minor Outlying Islands',
    value: 'um',
    flag: 'um',
  },
  {
    iso_3166_1: 'US',
    english_name: 'United States of America',
    text: 'United States of America',
    value: 'us',
    flag: 'us',
  },
  {
    iso_3166_1: 'UY',
    english_name: 'Uruguay',
    text: 'Uruguay',
    value: 'uy',
    flag: 'uy',
  },
  {
    iso_3166_1: 'UZ',
    english_name: 'Uzbekistan',
    text: 'Uzbekistan',
    value: 'uz',
    flag: 'uz',
  },
  {
    iso_3166_1: 'VA',
    english_name: 'Holy See',
    text: 'Holy See',
    value: 'va',
    flag: 'va',
  },
  {
    iso_3166_1: 'VC',
    english_name: 'St. Vincent and the Grenadines',
    text: 'St. Vincent and the Grenadines',
    value: 'vc',
    flag: 'vc',
  },
  {
    iso_3166_1: 'VE',
    english_name: 'Venezuela',
    text: 'Venezuela',
    value: 've',
    flag: 've',
  },
  {
    iso_3166_1: 'VG',
    english_name: 'British Virgin Islands',
    text: 'British Virgin Islands',
    value: 'vg',
    flag: 'vg',
  },
  {
    iso_3166_1: 'VI',
    english_name: 'US Virgin Islands',
    text: 'US Virgin Islands',
    value: 'vi',
    flag: 'vi',
  },
  {
    iso_3166_1: 'VN',
    english_name: 'Vietnam',
    text: 'Vietnam',
    value: 'vn',
    flag: 'vn',
  },
  {
    iso_3166_1: 'VU',
    english_name: 'Vanuatu',
    text: 'Vanuatu',
    value: 'vu',
    flag: 'vu',
  },
  {
    iso_3166_1: 'WF',
    english_name: 'Wallis and Futuna Islands',
    text: 'Wallis and Futuna Islands',
    value: 'wf',
    flag: 'wf',
  },
  {
    iso_3166_1: 'WS',
    english_name: 'Samoa',
    text: 'Samoa',
    value: 'ws',
    flag: 'ws',
  },
  {
    iso_3166_1: 'YE',
    english_name: 'Yemen',
    text: 'Yemen',
    value: 'ye',
    flag: 'ye',
  },
  {
    iso_3166_1: 'YT',
    english_name: 'Mayotte',
    text: 'Mayotte',
    value: 'yt',
    flag: 'yt',
  },
  {
    iso_3166_1: 'ZA',
    english_name: 'South Africa',
    text: 'South Africa',
    value: 'za',
    flag: 'za',
  },
  {
    iso_3166_1: 'ZM',
    english_name: 'Zambia',
    text: 'Zambia',
    value: 'zm',
    flag: 'zm',
  },
  {
    iso_3166_1: 'ZW',
    english_name: 'Zimbabwe',
    text: 'Zimbabwe',
    value: 'zw',
    flag: 'zw',
  },
  {
    iso_3166_1: 'KR',
    english_name: 'South Korea',
    text: 'South Korea',
    value: 'kr',
    flag: 'kr',
  },
  {
    iso_3166_1: 'XG',
    english_name: 'East Germany',
    text: 'East Germany',
    value: 'xg',
    flag: 'xg',
  },
  {
    iso_3166_1: 'SU',
    english_name: 'Soviet Union',
    text: 'Soviet Union',
    value: 'su',
    flag: 'su',
  },
  {
    iso_3166_1: 'SS',
    english_name: 'South Sudan',
    text: 'South Sudan',
    value: 'ss',
    flag: 'ss',
  },
];

export default countries;
