import { LanguagesModel } from '../models/LanguagesModel';

const languages: Array<LanguagesModel> = [
  {
    iso_639_1: 'xx',
    english_name: 'No Language',
    text: 'No Language',
    value: 'xx',
    key: 'xx',
    name: 'No Language',
  },
  {
    iso_639_1: 'aa',
    english_name: 'Afar',
    text: 'Afar',
    value: 'aa',
    key: 'aa',
    name: '',
  },
  {
    iso_639_1: 'af',
    english_name: 'Afrikaans',
    text: 'Afrikaans',
    value: 'af',
    key: 'af',
    name: 'Afrikaans',
  },
  {
    iso_639_1: 'ak',
    english_name: 'Akan',
    text: 'Akan',
    value: 'ak',
    key: 'ak',
    name: '',
  },
  {
    iso_639_1: 'an',
    english_name: 'Aragonese',
    text: 'Aragonese',
    value: 'an',
    key: 'an',
    name: '',
  },
  {
    iso_639_1: 'as',
    english_name: 'Assamese',
    text: 'Assamese',
    value: 'as',
    key: 'as',
    name: '',
  },
  {
    iso_639_1: 'av',
    english_name: 'Avaric',
    text: 'Avaric',
    value: 'av',
    key: 'av',
    name: '',
  },
  {
    iso_639_1: 'ae',
    english_name: 'Avestan',
    text: 'Avestan',
    value: 'ae',
    key: 'ae',
    name: '',
  },
  {
    iso_639_1: 'ay',
    english_name: 'Aymara',
    text: 'Aymara',
    value: 'ay',
    key: 'ay',
    name: '',
  },
  {
    iso_639_1: 'az',
    english_name: 'Azerbaijani',
    text: 'Azerbaijani',
    value: 'az',
    key: 'az',
    name: 'Azərbaycan',
  },
  {
    iso_639_1: 'ba',
    english_name: 'Bashkir',
    text: 'Bashkir',
    value: 'ba',
    key: 'ba',
    name: '',
  },
  {
    iso_639_1: 'bm',
    english_name: 'Bambara',
    text: 'Bambara',
    value: 'bm',
    key: 'bm',
    name: 'Bamanankan',
  },
  {
    iso_639_1: 'bi',
    english_name: 'Bislama',
    text: 'Bislama',
    value: 'bi',
    key: 'bi',
    name: '',
  },
  {
    iso_639_1: 'bo',
    english_name: 'Tibetan',
    text: 'Tibetan',
    value: 'bo',
    key: 'bo',
    name: '',
  },
  {
    iso_639_1: 'br',
    english_name: 'Breton',
    text: 'Breton',
    value: 'br',
    key: 'br',
    name: '',
  },
  {
    iso_639_1: 'ca',
    english_name: 'Catalan',
    text: 'Catalan',
    value: 'ca',
    key: 'ca',
    name: 'Català',
  },
  {
    iso_639_1: 'cs',
    english_name: 'Czech',
    text: 'Czech',
    value: 'cs',
    key: 'cs',
    name: 'Český',
  },
  {
    iso_639_1: 'ce',
    english_name: 'Chechen',
    text: 'Chechen',
    value: 'ce',
    key: 'ce',
    name: '',
  },
  {
    iso_639_1: 'cu',
    english_name: 'Slavic',
    text: 'Slavic',
    value: 'cu',
    key: 'cu',
    name: '',
  },
  {
    iso_639_1: 'cv',
    english_name: 'Chuvash',
    text: 'Chuvash',
    value: 'cv',
    key: 'cv',
    name: '',
  },
  {
    iso_639_1: 'kw',
    english_name: 'Cornish',
    text: 'Cornish',
    value: 'kw',
    key: 'kw',
    name: '',
  },
  {
    iso_639_1: 'co',
    english_name: 'Corsican',
    text: 'Corsican',
    value: 'co',
    key: 'co',
    name: '',
  },
  {
    iso_639_1: 'cr',
    english_name: 'Cree',
    text: 'Cree',
    value: 'cr',
    key: 'cr',
    name: '',
  },
  {
    iso_639_1: 'cy',
    english_name: 'Welsh',
    text: 'Welsh',
    value: 'cy',
    key: 'cy',
    name: 'Cymraeg',
  },
  {
    iso_639_1: 'da',
    english_name: 'Danish',
    text: 'Danish',
    value: 'da',
    key: 'da',
    name: 'Dansk',
  },
  {
    iso_639_1: 'de',
    english_name: 'German',
    text: 'German',
    value: 'de',
    key: 'de',
    name: 'Deutsch',
  },
  {
    iso_639_1: 'dv',
    english_name: 'Divehi',
    text: 'Divehi',
    value: 'dv',
    key: 'dv',
    name: '',
  },
  {
    iso_639_1: 'dz',
    english_name: 'Dzongkha',
    text: 'Dzongkha',
    value: 'dz',
    key: 'dz',
    name: '',
  },
  {
    iso_639_1: 'eo',
    english_name: 'Esperanto',
    text: 'Esperanto',
    value: 'eo',
    key: 'eo',
    name: 'Esperanto',
  },
  {
    iso_639_1: 'et',
    english_name: 'Estonian',
    text: 'Estonian',
    value: 'et',
    key: 'et',
    name: 'Eesti',
  },
  {
    iso_639_1: 'eu',
    english_name: 'Basque',
    text: 'Basque',
    value: 'eu',
    key: 'eu',
    name: 'euskera',
  },
  {
    iso_639_1: 'fo',
    english_name: 'Faroese',
    text: 'Faroese',
    value: 'fo',
    key: 'fo',
    name: '',
  },
  {
    iso_639_1: 'fj',
    english_name: 'Fijian',
    text: 'Fijian',
    value: 'fj',
    key: 'fj',
    name: '',
  },
  {
    iso_639_1: 'fi',
    english_name: 'Finnish',
    text: 'Finnish',
    value: 'fi',
    key: 'fi',
    name: 'suomi',
  },
  {
    iso_639_1: 'fr',
    english_name: 'French',
    text: 'French',
    value: 'fr',
    key: 'fr',
    name: 'Français',
  },
  {
    iso_639_1: 'fy',
    english_name: 'Frisian',
    text: 'Frisian',
    value: 'fy',
    key: 'fy',
    name: '',
  },
  {
    iso_639_1: 'ff',
    english_name: 'Fulah',
    text: 'Fulah',
    value: 'ff',
    key: 'ff',
    name: 'Fulfulde',
  },
  {
    iso_639_1: 'gd',
    english_name: 'Gaelic',
    text: 'Gaelic',
    value: 'gd',
    key: 'gd',
    name: '',
  },
  {
    iso_639_1: 'ga',
    english_name: 'Irish',
    text: 'Irish',
    value: 'ga',
    key: 'ga',
    name: 'Gaeilge',
  },
  {
    iso_639_1: 'gl',
    english_name: 'Galician',
    text: 'Galician',
    value: 'gl',
    key: 'gl',
    name: 'Galego',
  },
  {
    iso_639_1: 'gv',
    english_name: 'Manx',
    text: 'Manx',
    value: 'gv',
    key: 'gv',
    name: '',
  },
  {
    iso_639_1: 'gn',
    english_name: 'Guarani',
    text: 'Guarani',
    value: 'gn',
    key: 'gn',
    name: '',
  },
  {
    iso_639_1: 'gu',
    english_name: 'Gujarati',
    text: 'Gujarati',
    value: 'gu',
    key: 'gu',
    name: '',
  },
  {
    iso_639_1: 'ht',
    english_name: 'Haitian; Haitian Creole',
    text: 'Haitian; Haitian Creole',
    value: 'ht',
    key: 'ht',
    name: '',
  },
  {
    iso_639_1: 'ha',
    english_name: 'Hausa',
    text: 'Hausa',
    value: 'ha',
    key: 'ha',
    name: 'Hausa',
  },
  {
    iso_639_1: 'sh',
    english_name: 'Serbo-Croatian',
    text: 'Serbo-Croatian',
    value: 'sh',
    key: 'sh',
    name: '',
  },
  {
    iso_639_1: 'hz',
    english_name: 'Herero',
    text: 'Herero',
    value: 'hz',
    key: 'hz',
    name: '',
  },
  {
    iso_639_1: 'ho',
    english_name: 'Hiri Motu',
    text: 'Hiri Motu',
    value: 'ho',
    key: 'ho',
    name: '',
  },
  {
    iso_639_1: 'hr',
    english_name: 'Croatian',
    text: 'Croatian',
    value: 'hr',
    key: 'hr',
    name: 'Hrvatski',
  },
  {
    iso_639_1: 'hu',
    english_name: 'Hungarian',
    text: 'Hungarian',
    value: 'hu',
    key: 'hu',
    name: 'Magyar',
  },
  {
    iso_639_1: 'ig',
    english_name: 'Igbo',
    text: 'Igbo',
    value: 'ig',
    key: 'ig',
    name: '',
  },
  {
    iso_639_1: 'io',
    english_name: 'Ido',
    text: 'Ido',
    value: 'io',
    key: 'io',
    name: '',
  },
  {
    iso_639_1: 'ii',
    english_name: 'Yi',
    text: 'Yi',
    value: 'ii',
    key: 'ii',
    name: '',
  },
  {
    iso_639_1: 'iu',
    english_name: 'Inuktitut',
    text: 'Inuktitut',
    value: 'iu',
    key: 'iu',
    name: '',
  },
  {
    iso_639_1: 'ie',
    english_name: 'Interlingue',
    text: 'Interlingue',
    value: 'ie',
    key: 'ie',
    name: '',
  },
  {
    iso_639_1: 'ia',
    english_name: 'Interlingua',
    text: 'Interlingua',
    value: 'ia',
    key: 'ia',
    name: '',
  },
  {
    iso_639_1: 'id',
    english_name: 'Indonesian',
    text: 'Indonesian',
    value: 'id',
    key: 'id',
    name: 'Bahasa indonesia',
  },
  {
    iso_639_1: 'ik',
    english_name: 'Inupiaq',
    text: 'Inupiaq',
    value: 'ik',
    key: 'ik',
    name: '',
  },
  {
    iso_639_1: 'is',
    english_name: 'Icelandic',
    text: 'Icelandic',
    value: 'is',
    key: 'is',
    name: 'Íslenska',
  },
  {
    iso_639_1: 'it',
    english_name: 'Italian',
    text: 'Italian',
    value: 'it',
    key: 'it',
    name: 'Italiano',
  },
  {
    iso_639_1: 'jv',
    english_name: 'Javanese',
    text: 'Javanese',
    value: 'jv',
    key: 'jv',
    name: '',
  },
  {
    iso_639_1: 'ja',
    english_name: 'Japanese',
    text: 'Japanese',
    value: 'ja',
    key: 'ja',
    name: '日本語',
  },
  {
    iso_639_1: 'kl',
    english_name: 'Kalaallisut',
    text: 'Kalaallisut',
    value: 'kl',
    key: 'kl',
    name: '',
  },
  {
    iso_639_1: 'kn',
    english_name: 'Kannada',
    text: 'Kannada',
    value: 'kn',
    key: 'kn',
    name: '?????',
  },
  {
    iso_639_1: 'ks',
    english_name: 'Kashmiri',
    text: 'Kashmiri',
    value: 'ks',
    key: 'ks',
    name: '',
  },
  {
    iso_639_1: 'kr',
    english_name: 'Kanuri',
    text: 'Kanuri',
    value: 'kr',
    key: 'kr',
    name: '',
  },
  {
    iso_639_1: 'kk',
    english_name: 'Kazakh',
    text: 'Kazakh',
    value: 'kk',
    key: 'kk',
    name: 'қазақ',
  },
  {
    iso_639_1: 'km',
    english_name: 'Khmer',
    text: 'Khmer',
    value: 'km',
    key: 'km',
    name: '',
  },
  {
    iso_639_1: 'ki',
    english_name: 'Kikuyu',
    text: 'Kikuyu',
    value: 'ki',
    key: 'ki',
    name: '',
  },
  {
    iso_639_1: 'rw',
    english_name: 'Kinyarwanda',
    text: 'Kinyarwanda',
    value: 'rw',
    key: 'rw',
    name: 'Kinyarwanda',
  },
  {
    iso_639_1: 'ky',
    english_name: 'Kirghiz',
    text: 'Kirghiz',
    value: 'ky',
    key: 'ky',
    name: '??????',
  },
  {
    iso_639_1: 'kv',
    english_name: 'Komi',
    text: 'Komi',
    value: 'kv',
    key: 'kv',
    name: '',
  },
  {
    iso_639_1: 'kg',
    english_name: 'Kongo',
    text: 'Kongo',
    value: 'kg',
    key: 'kg',
    name: '',
  },
  {
    iso_639_1: 'ko',
    english_name: 'Korean',
    text: 'Korean',
    value: 'ko',
    key: 'ko',
    name: '한국어/조선말',
  },
  {
    iso_639_1: 'kj',
    english_name: 'Kuanyama',
    text: 'Kuanyama',
    value: 'kj',
    key: 'kj',
    name: '',
  },
  {
    iso_639_1: 'ku',
    english_name: 'Kurdish',
    text: 'Kurdish',
    value: 'ku',
    key: 'ku',
    name: '',
  },
  {
    iso_639_1: 'lo',
    english_name: 'Lao',
    text: 'Lao',
    value: 'lo',
    key: 'lo',
    name: '',
  },
  {
    iso_639_1: 'la',
    english_name: 'Latin',
    text: 'Latin',
    value: 'la',
    key: 'la',
    name: 'Latin',
  },
  {
    iso_639_1: 'lv',
    english_name: 'Latvian',
    text: 'Latvian',
    value: 'lv',
    key: 'lv',
    name: 'Latviešu',
  },
  {
    iso_639_1: 'li',
    english_name: 'Limburgish',
    text: 'Limburgish',
    value: 'li',
    key: 'li',
    name: '',
  },
  {
    iso_639_1: 'ln',
    english_name: 'Lingala',
    text: 'Lingala',
    value: 'ln',
    key: 'ln',
    name: '',
  },
  {
    iso_639_1: 'lt',
    english_name: 'Lithuanian',
    text: 'Lithuanian',
    value: 'lt',
    key: 'lt',
    name: 'Lietuvių',
  },
  {
    iso_639_1: 'lb',
    english_name: 'Letzeburgesch',
    text: 'Letzeburgesch',
    value: 'lb',
    key: 'lb',
    name: '',
  },
  {
    iso_639_1: 'lu',
    english_name: 'Luba-Katanga',
    text: 'Luba-Katanga',
    value: 'lu',
    key: 'lu',
    name: '',
  },
  {
    iso_639_1: 'lg',
    english_name: 'Ganda',
    text: 'Ganda',
    value: 'lg',
    key: 'lg',
    name: '',
  },
  {
    iso_639_1: 'mh',
    english_name: 'Marshall',
    text: 'Marshall',
    value: 'mh',
    key: 'mh',
    name: '',
  },
  {
    iso_639_1: 'ml',
    english_name: 'Malayalam',
    text: 'Malayalam',
    value: 'ml',
    key: 'ml',
    name: '',
  },
  {
    iso_639_1: 'mr',
    english_name: 'Marathi',
    text: 'Marathi',
    value: 'mr',
    key: 'mr',
    name: '',
  },
  {
    iso_639_1: 'mg',
    english_name: 'Malagasy',
    text: 'Malagasy',
    value: 'mg',
    key: 'mg',
    name: '',
  },
  {
    iso_639_1: 'mt',
    english_name: 'Maltese',
    text: 'Maltese',
    value: 'mt',
    key: 'mt',
    name: 'Malti',
  },
  {
    iso_639_1: 'mo',
    english_name: 'Moldavian',
    text: 'Moldavian',
    value: 'mo',
    key: 'mo',
    name: '',
  },
  {
    iso_639_1: 'mn',
    english_name: 'Mongolian',
    text: 'Mongolian',
    value: 'mn',
    key: 'mn',
    name: '',
  },
  {
    iso_639_1: 'mi',
    english_name: 'Maori',
    text: 'Maori',
    value: 'mi',
    key: 'mi',
    name: '',
  },
  {
    iso_639_1: 'ms',
    english_name: 'Malay',
    text: 'Malay',
    value: 'ms',
    key: 'ms',
    name: 'Bahasa melayu',
  },
  {
    iso_639_1: 'my',
    english_name: 'Burmese',
    text: 'Burmese',
    value: 'my',
    key: 'my',
    name: '',
  },
  {
    iso_639_1: 'na',
    english_name: 'Nauru',
    text: 'Nauru',
    value: 'na',
    key: 'na',
    name: '',
  },
  {
    iso_639_1: 'nv',
    english_name: 'Navajo',
    text: 'Navajo',
    value: 'nv',
    key: 'nv',
    name: '',
  },
  {
    iso_639_1: 'nr',
    english_name: 'Ndebele',
    text: 'Ndebele',
    value: 'nr',
    key: 'nr',
    name: '',
  },
  {
    iso_639_1: 'nd',
    english_name: 'Ndebele',
    text: 'Ndebele',
    value: 'nd',
    key: 'nd',
    name: '',
  },
  {
    iso_639_1: 'ng',
    english_name: 'Ndonga',
    text: 'Ndonga',
    value: 'ng',
    key: 'ng',
    name: '',
  },
  {
    iso_639_1: 'ne',
    english_name: 'Nepali',
    text: 'Nepali',
    value: 'ne',
    key: 'ne',
    name: '',
  },
  {
    iso_639_1: 'nl',
    english_name: 'Dutch',
    text: 'Dutch',
    value: 'nl',
    key: 'nl',
    name: 'Nederlands',
  },
  {
    iso_639_1: 'nn',
    english_name: 'Norwegian Nynorsk',
    text: 'Norwegian Nynorsk',
    value: 'nn',
    key: 'nn',
    name: '',
  },
  {
    iso_639_1: 'nb',
    english_name: 'Norwegian Bokmål',
    text: 'Norwegian Bokmål',
    value: 'nb',
    key: 'nb',
    name: 'Bokmål',
  },
  {
    iso_639_1: 'no',
    english_name: 'Norwegian',
    text: 'Norwegian',
    value: 'no',
    key: 'no',
    name: 'Norsk',
  },
  {
    iso_639_1: 'ny',
    english_name: 'Chichewa; Nyanja',
    text: 'Chichewa; Nyanja',
    value: 'ny',
    key: 'ny',
    name: '',
  },
  {
    iso_639_1: 'oc',
    english_name: 'Occitan',
    text: 'Occitan',
    value: 'oc',
    key: 'oc',
    name: '',
  },
  {
    iso_639_1: 'oj',
    english_name: 'Ojibwa',
    text: 'Ojibwa',
    value: 'oj',
    key: 'oj',
    name: '',
  },
  {
    iso_639_1: 'or',
    english_name: 'Oriya',
    text: 'Oriya',
    value: 'or',
    key: 'or',
    name: '',
  },
  {
    iso_639_1: 'om',
    english_name: 'Oromo',
    text: 'Oromo',
    value: 'om',
    key: 'om',
    name: '',
  },
  {
    iso_639_1: 'os',
    english_name: 'Ossetian; Ossetic',
    text: 'Ossetian; Ossetic',
    value: 'os',
    key: 'os',
    name: '',
  },
  {
    iso_639_1: 'pi',
    english_name: 'Pali',
    text: 'Pali',
    value: 'pi',
    key: 'pi',
    name: '',
  },
  {
    iso_639_1: 'pl',
    english_name: 'Polish',
    text: 'Polish',
    value: 'pl',
    key: 'pl',
    name: 'Polski',
  },
  {
    iso_639_1: 'pt',
    english_name: 'Portuguese',
    text: 'Portuguese',
    value: 'pt',
    key: 'pt',
    name: 'Português',
  },
  {
    iso_639_1: 'qu',
    english_name: 'Quechua',
    text: 'Quechua',
    value: 'qu',
    key: 'qu',
    name: '',
  },
  {
    iso_639_1: 'rm',
    english_name: 'Raeto-Romance',
    text: 'Raeto-Romance',
    value: 'rm',
    key: 'rm',
    name: '',
  },
  {
    iso_639_1: 'ro',
    english_name: 'Romanian',
    text: 'Romanian',
    value: 'ro',
    key: 'ro',
    name: 'Română',
  },
  {
    iso_639_1: 'rn',
    english_name: 'Rundi',
    text: 'Rundi',
    value: 'rn',
    key: 'rn',
    name: 'Kirundi',
  },
  {
    iso_639_1: 'ru',
    english_name: 'Russian',
    text: 'Russian',
    value: 'ru',
    key: 'ru',
    name: 'Pусский',
  },
  {
    iso_639_1: 'sg',
    english_name: 'Sango',
    text: 'Sango',
    value: 'sg',
    key: 'sg',
    name: '',
  },
  {
    iso_639_1: 'sa',
    english_name: 'Sanskrit',
    text: 'Sanskrit',
    value: 'sa',
    key: 'sa',
    name: '',
  },
  {
    iso_639_1: 'si',
    english_name: 'Sinhalese',
    text: 'Sinhalese',
    value: 'si',
    key: 'si',
    name: 'සිංහල',
  },
  {
    iso_639_1: 'sk',
    english_name: 'Slovak',
    text: 'Slovak',
    value: 'sk',
    key: 'sk',
    name: 'Slovenčina',
  },
  {
    iso_639_1: 'sl',
    english_name: 'Slovenian',
    text: 'Slovenian',
    value: 'sl',
    key: 'sl',
    name: 'Slovenščina',
  },
  {
    iso_639_1: 'se',
    english_name: 'Northern Sami',
    text: 'Northern Sami',
    value: 'se',
    key: 'se',
    name: '',
  },
  {
    iso_639_1: 'sm',
    english_name: 'Samoan',
    text: 'Samoan',
    value: 'sm',
    key: 'sm',
    name: '',
  },
  {
    iso_639_1: 'sn',
    english_name: 'Shona',
    text: 'Shona',
    value: 'sn',
    key: 'sn',
    name: '',
  },
  {
    iso_639_1: 'sd',
    english_name: 'Sindhi',
    text: 'Sindhi',
    value: 'sd',
    key: 'sd',
    name: '',
  },
  {
    iso_639_1: 'so',
    english_name: 'Somali',
    text: 'Somali',
    value: 'so',
    key: 'so',
    name: 'Somali',
  },
  {
    iso_639_1: 'st',
    english_name: 'Sotho',
    text: 'Sotho',
    value: 'st',
    key: 'st',
    name: '',
  },
  {
    iso_639_1: 'es',
    english_name: 'Spanish',
    text: 'Spanish',
    value: 'es',
    key: 'es',
    name: 'Español',
  },
  {
    iso_639_1: 'sq',
    english_name: 'Albanian',
    text: 'Albanian',
    value: 'sq',
    key: 'sq',
    name: 'shqip',
  },
  {
    iso_639_1: 'sc',
    english_name: 'Sardinian',
    text: 'Sardinian',
    value: 'sc',
    key: 'sc',
    name: '',
  },
  {
    iso_639_1: 'sr',
    english_name: 'Serbian',
    text: 'Serbian',
    value: 'sr',
    key: 'sr',
    name: 'Srpski',
  },
  {
    iso_639_1: 'ss',
    english_name: 'Swati',
    text: 'Swati',
    value: 'ss',
    key: 'ss',
    name: '',
  },
  {
    iso_639_1: 'su',
    english_name: 'Sundanese',
    text: 'Sundanese',
    value: 'su',
    key: 'su',
    name: '',
  },
  {
    iso_639_1: 'sw',
    english_name: 'Swahili',
    text: 'Swahili',
    value: 'sw',
    key: 'sw',
    name: 'Kiswahili',
  },
  {
    iso_639_1: 'sv',
    english_name: 'Swedish',
    text: 'Swedish',
    value: 'sv',
    key: 'sv',
    name: 'svenska',
  },
  {
    iso_639_1: 'ty',
    english_name: 'Tahitian',
    text: 'Tahitian',
    value: 'ty',
    key: 'ty',
    name: '',
  },
  {
    iso_639_1: 'ta',
    english_name: 'Tamil',
    text: 'Tamil',
    value: 'ta',
    key: 'ta',
    name: 'தமிழ்',
  },
  {
    iso_639_1: 'tt',
    english_name: 'Tatar',
    text: 'Tatar',
    value: 'tt',
    key: 'tt',
    name: '',
  },
  {
    iso_639_1: 'te',
    english_name: 'Telugu',
    text: 'Telugu',
    value: 'te',
    key: 'te',
    name: 'తెలుగు',
  },
  {
    iso_639_1: 'tg',
    english_name: 'Tajik',
    text: 'Tajik',
    value: 'tg',
    key: 'tg',
    name: '',
  },
  {
    iso_639_1: 'tl',
    english_name: 'Tagalog',
    text: 'Tagalog',
    value: 'tl',
    key: 'tl',
    name: '',
  },
  {
    iso_639_1: 'th',
    english_name: 'Thai',
    text: 'Thai',
    value: 'th',
    key: 'th',
    name: 'ภาษาไทย',
  },
  {
    iso_639_1: 'ti',
    english_name: 'Tigrinya',
    text: 'Tigrinya',
    value: 'ti',
    key: 'ti',
    name: '',
  },
  {
    iso_639_1: 'to',
    english_name: 'Tonga',
    text: 'Tonga',
    value: 'to',
    key: 'to',
    name: '',
  },
  {
    iso_639_1: 'tn',
    english_name: 'Tswana',
    text: 'Tswana',
    value: 'tn',
    key: 'tn',
    name: '',
  },
  {
    iso_639_1: 'ts',
    english_name: 'Tsonga',
    text: 'Tsonga',
    value: 'ts',
    key: 'ts',
    name: '',
  },
  {
    iso_639_1: 'tk',
    english_name: 'Turkmen',
    text: 'Turkmen',
    value: 'tk',
    key: 'tk',
    name: '',
  },
  {
    iso_639_1: 'tr',
    english_name: 'Turkish',
    text: 'Turkish',
    value: 'tr',
    key: 'tr',
    name: 'Türkçe',
  },
  {
    iso_639_1: 'tw',
    english_name: 'Twi',
    text: 'Twi',
    value: 'tw',
    key: 'tw',
    name: '',
  },
  {
    iso_639_1: 'ug',
    english_name: 'Uighur',
    text: 'Uighur',
    value: 'ug',
    key: 'ug',
    name: '',
  },
  {
    iso_639_1: 'uk',
    english_name: 'Ukrainian',
    text: 'Ukrainian',
    value: 'uk',
    key: 'uk',
    name: 'Український',
  },
  {
    iso_639_1: 'ur',
    english_name: 'Urdu',
    text: 'Urdu',
    value: 'ur',
    key: 'ur',
    name: 'اردو',
  },
  {
    iso_639_1: 'uz',
    english_name: 'Uzbek',
    text: 'Uzbek',
    value: 'uz',
    key: 'uz',
    name: 'ozbek',
  },
  {
    iso_639_1: 've',
    english_name: 'Venda',
    text: 'Venda',
    value: 've',
    key: 've',
    name: '',
  },
  {
    iso_639_1: 'vi',
    english_name: 'Vietnamese',
    text: 'Vietnamese',
    value: 'vi',
    key: 'vi',
    name: 'Tiếng Việt',
  },
  {
    iso_639_1: 'vo',
    english_name: 'Volapük',
    text: 'Volapük',
    value: 'vo',
    key: 'vo',
    name: '',
  },
  {
    iso_639_1: 'wa',
    english_name: 'Walloon',
    text: 'Walloon',
    value: 'wa',
    key: 'wa',
    name: '',
  },
  {
    iso_639_1: 'wo',
    english_name: 'Wolof',
    text: 'Wolof',
    value: 'wo',
    key: 'wo',
    name: 'Wolof',
  },
  {
    iso_639_1: 'xh',
    english_name: 'Xhosa',
    text: 'Xhosa',
    value: 'xh',
    key: 'xh',
    name: '',
  },
  {
    iso_639_1: 'yi',
    english_name: 'Yiddish',
    text: 'Yiddish',
    value: 'yi',
    key: 'yi',
    name: '',
  },
  {
    iso_639_1: 'za',
    english_name: 'Zhuang',
    text: 'Zhuang',
    value: 'za',
    key: 'za',
    name: '',
  },
  {
    iso_639_1: 'zu',
    english_name: 'Zulu',
    text: 'Zulu',
    value: 'zu',
    key: 'zu',
    name: 'isiZulu',
  },
  {
    iso_639_1: 'ab',
    english_name: 'Abkhazian',
    text: 'Abkhazian',
    value: 'ab',
    key: 'ab',
    name: '',
  },
  {
    iso_639_1: 'zh',
    english_name: 'Mandarin',
    text: 'Mandarin',
    value: 'zh',
    key: 'zh',
    name: '普通话',
  },
  {
    iso_639_1: 'ps',
    english_name: 'Pushto',
    text: 'Pushto',
    value: 'ps',
    key: 'ps',
    name: 'پښتو',
  },
  {
    iso_639_1: 'am',
    english_name: 'Amharic',
    text: 'Amharic',
    value: 'am',
    key: 'am',
    name: '',
  },
  {
    iso_639_1: 'ar',
    english_name: 'Arabic',
    text: 'Arabic',
    value: 'ar',
    key: 'ar',
    name: 'العربية',
  },
  {
    iso_639_1: 'bg',
    english_name: 'Bulgarian',
    text: 'Bulgarian',
    value: 'bg',
    key: 'bg',
    name: 'български език',
  },
  {
    iso_639_1: 'cn',
    english_name: 'Cantonese',
    text: 'Cantonese',
    value: 'cn',
    key: 'cn',
    name: '广州话 / 廣州話',
  },
  {
    iso_639_1: 'mk',
    english_name: 'Macedonian',
    text: 'Macedonian',
    value: 'mk',
    key: 'mk',
    name: '',
  },
  {
    iso_639_1: 'el',
    english_name: 'Greek',
    text: 'Greek',
    value: 'el',
    key: 'el',
    name: 'ελληνικά',
  },
  {
    iso_639_1: 'fa',
    english_name: 'Persian',
    text: 'Persian',
    value: 'fa',
    key: 'fa',
    name: 'فارسی',
  },
  {
    iso_639_1: 'he',
    english_name: 'Hebrew',
    text: 'Hebrew',
    value: 'he',
    key: 'he',
    name: 'עִבְרִית',
  },
  {
    iso_639_1: 'hi',
    english_name: 'Hindi',
    text: 'Hindi',
    value: 'hi',
    key: 'hi',
    name: 'हिन्दी',
  },
  {
    iso_639_1: 'hy',
    english_name: 'Armenian',
    text: 'Armenian',
    value: 'hy',
    key: 'hy',
    name: '',
  },
  {
    iso_639_1: 'en',
    english_name: 'English',
    text: 'English',
    value: 'en',
    key: 'en',
    name: 'English',
  },
  {
    iso_639_1: 'ee',
    english_name: 'Ewe',
    text: 'Ewe',
    value: 'ee',
    key: 'ee',
    name: 'Èʋegbe',
  },
  {
    iso_639_1: 'ka',
    english_name: 'Georgian',
    text: 'Georgian',
    value: 'ka',
    key: 'ka',
    name: 'ქართული',
  },
  {
    iso_639_1: 'pa',
    english_name: 'Punjabi',
    text: 'Punjabi',
    value: 'pa',
    key: 'pa',
    name: 'ਪੰਜਾਬੀ',
  },
  {
    iso_639_1: 'bn',
    english_name: 'Bengali',
    text: 'Bengali',
    value: 'bn',
    key: 'bn',
    name: 'বাংলা',
  },
  {
    iso_639_1: 'bs',
    english_name: 'Bosnian',
    text: 'Bosnian',
    value: 'bs',
    key: 'bs',
    name: 'Bosanski',
  },
  {
    iso_639_1: 'ch',
    english_name: 'Chamorro',
    text: 'Chamorro',
    value: 'ch',
    key: 'ch',
    name: "Finu' Chamorro",
  },
  {
    iso_639_1: 'be',
    english_name: 'Belarusian',
    text: 'Belarusian',
    value: 'be',
    key: 'be',
    name: 'беларуская мова',
  },
  {
    iso_639_1: 'yo',
    english_name: 'Yoruba',
    text: 'Yoruba',
    value: 'yo',
    key: 'yo',
    name: 'Èdè Yorùbá',
  },
];

export default languages;
